package main

const page = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VSME 双主机远程维修 v2</title><style>
*{box-sizing:border-box}body{margin:0;background:#eef2f7;color:#172841;font:15px system-ui,'Microsoft YaHei',sans-serif}header{background:#182744;color:#fff;padding:26px 5vw}h1{font-size:25px;margin:0 0 9px}header small{color:#afc2db}main{max-width:1360px;margin:auto;padding:24px}section{background:white;border:1px solid #dbe2ed;border-radius:12px;padding:22px;margin-bottom:20px}h2{font-size:18px;margin:0 0 14px}button{padding:10px 16px;border:1px solid #c4d0e0;background:white;border-radius:6px;cursor:pointer;color:#192e50;margin:4px 6px 4px 0}button.primary{background:#2563d9;color:white;border-color:#2563d9}.danger{color:#be123c}button:disabled{opacity:.5;cursor:default}textarea,input{width:100%;padding:12px;border:1px solid #bccce0;border-radius:6px;font:14px Consolas,monospace}textarea{height:96px;resize:vertical}.muted{color:#637289;font-size:13px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;padding:12px 10px;border-bottom:1px solid #e3e8f0;vertical-align:top;white-space:pre-line}tr.selected{background:#e8f0ff}tbody tr{cursor:pointer}.offline{color:#8391a5}.table{overflow:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#152034;color:#dce8fa;padding:18px;max-height:360px;overflow:auto;border-radius:8px;font:13px Consolas,monospace}#error{color:#b91c1c;white-space:pre-wrap}#state{color:#4fe0ac}.row{display:flex;gap:14px;align-items:center;flex-wrap:wrap}.right{margin-left:auto}[hidden]{display:none!important}.notice{background:#f0f5ff;border-left:3px solid #397ce3;padding:12px}.ok{color:#16754b}summary{cursor:pointer}label{display:block;margin:12px 0 8px}</style>
<header><div class="row"><div><h1>VSME 双主机远程维修 <small>v2.1.1</small></h1><div id="state">正在读取状态…</div></div><button class="right danger" id="stop">停止并关闭权限</button></div><p id="identity"></p><small id="lifecycle">正在读取权限模式…</small></header>
<main><p id="error" role="alert"></p><section id="controller" hidden><h2>接入设备 · 点击选择目标</h2><p class="muted">本机与另一台 Windows 控制端可互控；其他 Windows / Mac 只接受控制。同一台电脑的维修任务按顺序执行。</p><div class="table"><table><thead><tr><th>备注 / 电脑名</th><th>系统 / 运行账号</th><th>本机 IP / 接入来源</th><th>本次接入时间</th><th>最近在线</th><th>状态</th></tr></thead><tbody id="peers"></tbody></table></div><p id="target" class="notice">请选择目标</p><button class="primary" id="info">读取所选电脑信息</button><button id="prompt">复制本机＋所选电脑提示词</button><button id="revoke" class="danger">断开所选电脑</button><details><summary>所选电脑主动发送的信息</summary><p id="reportedAt" class="muted"></p><pre id="reportedInfo">尚未主动发送；可点击上方按钮远程读取。</pre></details><h2 style="margin-top:22px">维修命令</h2><textarea id="command" placeholder="Windows 使用 PowerShell；Mac 使用 zsh。命令只发送给上方选中的电脑。"></textarea><button class="primary" id="run">执行并查看进度</button><button id="cancel">取消当前任务</button><h2 style="margin-top:22px">文件传输</h2><input id="path" placeholder="发送：控制端本机绝对路径；取回：所选副机绝对路径"><button id="send">发送到所选副机</button><button id="get">从所选副机取回</button><p class="muted">通过副机主动建立的加密连接传输，校验 SHA-256；最大 2 GB。接收使用独立名称，不覆盖原文件。</p><h2>任务结果</h2><select id="jobs" style="padding:10px;width:100%"></select><pre id="output">尚无任务</pre></section>
<section id="serverPanel" hidden><h2>常驻主机 / 服务器 · 既有 SSH 通道</h2><p class="muted">只检查现有服务端口是否可达，不登录、不安装软件、不改服务器设置。“服务可达”不代表具备维修权限或 CPU / 磁盘健康。</p><div id="serverList">尚未添加服务器</div><label for="serverName">服务器备注</label><input id="serverName" placeholder="例如：全天候文件服务器"><label for="serverHost">服务器 IP 或完整电脑名</label><input id="serverHost" placeholder="待确认，请不要把登录账号当作电脑名"><label for="serverPort">现有服务端口：共享 445 / SSH 22 / 远程桌面 3389</label><input id="serverPort" type="number" min="1" max="65535" value="445"><button id="serverAdd">添加只读状态监测</button><p class="muted">每 5 秒检测；本机软件关闭即停止检测。这里只保存连接地址，不保存密码。</p></section>
<section><h2>电脑备注（可选，只填名字）</h2><p class="muted">此区域用于识别这台电脑，不要粘贴连接文字。接入时自动发送电脑名、账号、系统和 IP；下方按钮另行发送 CPU、内存、磁盘可用空间和启动时间，不读取密码或浏览器数据。</p><label for="note">你的名字 / 电脑备注</label><input id="note" maxlength="80" placeholder="例如：兰 / 李嘉彰的 Mac"><button id="report">保存名字并发送本机信息</button><p id="reportStatus" class="ok"></p></section>
<section><h2>本机被控连接 · 自动找地址</h2><div id="connections">正在寻找指定的两台 Windows 控制端…</div><p class="muted">v2.1：已知地址失败后，仅在已知局域网段查找维修端口，并核验原有主控证书。无需关闭防火墙。断线先停止任务；明确撤销后须重新打开。</p><details><summary>找不到？手动填写主控 IP</summary><label for="manualController">选择主控</label><select id="manualController"><option value="CONTROL-B">CONTROL-B</option><option value="CONTROL-A">CONTROL-A</option></select><label for="manualIP">主控当前的局域网 IPv4 地址</label><input id="manualIP" maxlength="15" placeholder="例如 10.77.0.14，不用输入网址或端口"><button id="manualSave">保存并重连</button><button id="manualAuto">恢复自动查找</button><p id="manualStatus" class="ok"></p><p class="muted">这里只改变寻找地址，不能更换授权主控或关闭证书校验。</p></details></section>
<section id="joinPanel"><h2>连接两台主控 · 粘贴管理员的连接文字</h2><p class="muted">① 先复制管理员发来的整段文字。② 点“一键粘贴并连接”，按钮会自动读取剪贴板，不用填写名字。看到 2/2 才表示两台都已接通。</p><button class="primary" id="pasteAddress">一键粘贴并连接</button><label for="sharedAddress">连接文字专用框（浏览器不允许自动读取时使用，不是名字）</label><textarea id="sharedAddress" maxlength="16384" placeholder="请按 Command+V 粘贴管理员发来的整段连接文字，然后点下方“导入并连接”"></textarea><button id="importAddress">导入并连接</button><p id="importStatus" role="status" class="ok"></p></section>
<section id="addresses" hidden><h2>双主控连接分享</h2><p id="urls"></p><button id="shareAddress">一键复制双主控连接文字</button><p class="muted">先核验另一台主控，再生成两台地址。对方只需粘贴整段文字、导入并连接，看到 2/2 才表示两台都已接通。IP 变化后重新复制即可；文字不含私钥。副机仍需要能访问主控 TCP 45842；不能绕过访客隔离。</p></section></main>
<script>
const terminalLifecycle=false;
let key=location.hash.slice(1);try{if(key)sessionStorage.setItem('vsme-local-key',key);else key=sessionStorage.getItem('vsme-local-key')||'';history.replaceState(null,'',location.pathname)}catch(e){}
let selected='',jobID='',closing=false,currentPeer=null,noteLoaded=false,refreshing=false;const serverInfo={};
const $=id=>document.getElementById(id);
const date=s=>s&&!s.startsWith('0001')?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—';
const osName=s=>s==='darwin'?'Mac':s==='windows'?'Windows':s;
async function api(name,data={}){const r=await fetch('/api/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,...data})});const v=await r.json();if(!r.ok)throw Error(v.error||'请求失败');return v}
function text(tag,s){const e=document.createElement(tag);e.textContent=s;return e}
function error(e){$('error').textContent=e.message||String(e)}
function need(){if(!currentPeer||currentPeer.revoked)throw Error('请先选择在线电脑')}
async function start(op){need();const targetID=selected;const j=await api('job',{agent:targetID,op,command:$('command').value,path:$('path').value});if(selected===targetID)jobID=j.id;await refresh()}
async function refresh(){if(closing||refreshing)return;refreshing=true;try{
 await api('lease');const s=await api('status');const connected=(s.connections||[]).filter(c=>c.state==='connected').length;const inbound=(s.peers||[]).some(p=>!p.revoked&&(s.connections||[]).some(c=>(c.name||'').toUpperCase()===p.machine.name.toUpperCase())&&p.machine.name.toUpperCase()!==s.machine.name.toUpperCase());const ready=s.role==='controller'?connected>0&&inbound:connected===2;$('state').style.color=ready?'#4fe0ac':'#ffd074';$('state').textContent=s.role==='controller'?(ready?'双向连接已就绪 · 另一主控可互控':'另一主控连接未齐 · 正在自动重试'):connected===2?'2/2 主控已连接 · 两台都可以维修，请保持程序打开':connected+'/2 主控已连接 · 尚未全部接通，自动重试中；也可粘贴双主控连接文字';
 if(s.role!=='controller'&&!$('joinPanel').dataset.moved){$('error').after($('joinPanel'));$('joinPanel').dataset.moved='1'}
 $('stop').textContent=s.role==='controller'?'关闭管理界面（SSH 保留）':'停止并关闭副机权限';$('lifecycle').textContent=s.role==='controller'?'公开候选版只管理临时连接，不附带或安装常驻 SSH 授权。':terminalLifecycle?'苹果连接稳定修复版 2.1.1：保持启动终端打开才授权。网页关闭、刷新或切后台不会断线；关闭终端、按 Control+C 或点“停止授权”才结束。无后台服务或开机自启。':'保持程序和本页面打开才授权；关闭后断开，不安装服务、不设开机自启。';
 $('identity').textContent=(s.machine.note?s.machine.note+' | ':'')+s.machine.name+' | '+s.machine.user+' | '+s.machine.ips.join(', ');
 if(!noteLoaded){$('note').value=s.machine.note||'';noteLoaded=true}
 $('serverPanel').hidden=s.role!=='controller';
 $('serverList').replaceChildren();for(const server of s.servers||[]){const row=document.createElement('div');row.className='notice';row.append(text('strong',server.name+' · '+server.host+':'+server.port),text('p',server.state+' · 本次检测 '+date(server.checked)+' · 最近可达 '+date(server.last_seen)+(server.state==='服务可达'?' · '+server.latency_ms+' ms':'')));if(server.error)row.append(text('p',server.error));const remove=text('button','移除此监测项');remove.onclick=()=>api('server-remove',{agent:server.id}).then(refresh).catch(error);row.append(remove);if(server.port===22&&['10.77.0.11','10.77.0.12','10.77.0.13','CONTROL-A','VSME','CONTROL-B'].includes(server.host)){const inspect=text('button','通过现有 SSH 读取信息');inspect.onclick=async()=>{inspect.disabled=true;try{const v=await api('ssh-info',{host:server.host});serverInfo[server.id]='SSH 认证成功 · '+date(v.time)+'\n'+v.information;await refresh()}catch(e){serverInfo[server.id]=e.message;error(e)}finally{inspect.disabled=false}};row.append(inspect)}if(serverInfo[server.id])row.append(text('pre',serverInfo[server.id]));$('serverList').append(row)}if(!(s.servers||[]).length)$('serverList').append(text('p','尚未添加，等待确认服务器地址。'));
 $('controller').hidden=s.role!=='controller';$('addresses').hidden=s.role!=='controller';if(s.urls)$('urls').textContent=s.urls.join('   ');
 $('connections').replaceChildren();for(const c of s.connections||[]){$('connections').append(text('p',(c.name?c.name+' · ':'')+c.controller+' — '+({connecting:'连接中',connected:'已连接',discovering:'自动查找主控新地址',disconnected:'连接中断',closed:'本次连接已关闭'}[c.state]||c.state)+' · 接入 '+date(c.joined)+(c.error?' · '+c.error:'')))}
 if(!(s.connections||[]).length)$('connections').append(text('p','等待指定控制端上线…'));
 if(s.peers){const ps=s.peers.sort((a,b)=>Number(a.revoked)-Number(b.revoked)||new Date(b.joined)-new Date(a.joined));$('peers').replaceChildren();for(const p of ps){const tr=document.createElement('tr');tr.className=(p.id===selected?'selected ':'')+(p.revoked?'offline':'');const name=text('td',p.machine.note||p.machine.name);name.append(text('div',p.machine.note?p.machine.name:''),text('small','会话 '+p.id));tr.append(name,text('td',osName(p.machine.os)+' / '+p.machine.arch+'\n'+p.machine.user+'\n'+(p.machine.admin?'管理员':'普通用户')),text('td',p.machine.ips.join(', ')+'\n来源 '+p.address),text('td',date(p.joined)),text('td',date(p.last)),text('td',p.revoked?'已断开':'在线'));tr.onclick=()=>{selected=p.id;jobID='';refresh()};$('peers').append(tr)}
 const p=ps.find(x=>x.id===selected);currentPeer=p||null;$('target').textContent=p?'当前目标：'+(p.machine.note||p.machine.name)+' · '+p.machine.name+' · '+osName(p.machine.os)+' · '+p.id+(p.revoked?'（已断开）':''):'请选择目标';
 for(const id of ['info','prompt','revoke','run','send','get','cancel'])$(id).disabled=!p||p.revoked;
 $('reportedAt').textContent=p?'发送时间：'+date(p.reported):'';$('reportedInfo').textContent=p&&p.information?p.information:'尚未主动发送；可点击“读取所选电脑信息”。';
 const jobs=p?p.jobs:[];$('jobs').replaceChildren();for(const j of jobs){const opt=text('option',j.op+' · '+j.state+' · '+j.id);opt.value=j.id;$('jobs').append(opt)}if(!jobID&&jobs.length)jobID=jobs[jobs.length-1].id;$('jobs').value=jobID;const j=jobs.find(x=>x.id===jobID);$('output').textContent=j?('状态：'+j.state+' / 退出码：'+j.exit+(j.size?' / 进度：'+j.progress+' / '+j.size+' bytes':'')+'\n'+j.output+(j.path?'\n文件：'+j.path:'')):'尚无任务'
 }
 }catch(e){$('state').textContent='状态读取失败，无法确认当前连接，请查看提示';$('state').style.color='#ffd074';error(e)}finally{refreshing=false}}
$('jobs').onchange=()=>{jobID=$('jobs').value;refresh()};$('info').onclick=()=>start('info').catch(error);$('run').onclick=()=>start('shell').catch(error);$('send').onclick=()=>start('put').catch(error);$('get').onclick=()=>start('get').catch(error);$('cancel').onclick=()=>api('cancel',{agent:selected,job:jobID}).catch(error);$('revoke').onclick=()=>api('revoke',{agent:selected}).then(refresh).catch(error);
$('prompt').onclick=async()=>{try{need();const p=await api('prompt',{agent:selected});await navigator.clipboard.writeText(p.text);$('target').textContent='已复制所选电脑的接通提示词'}catch(e){error(e)}};
$('report').onclick=async()=>{const b=$('report');b.disabled=true;$('reportStatus').textContent='正在读取本机信息…';try{const r=await api('report',{note:$('note').value});$('reportStatus').textContent='备注已保存；本机信息已发送给 '+r.sent+' 台在线控制端。'+(r.sent===0?'请确认控制端已打开。':'')+(r.errors.length?' '+r.errors.join('；'):'');await refresh()}catch(e){error(e);$('reportStatus').textContent='信息未发送'}finally{b.disabled=false}};
$('serverAdd').onclick=()=>api('server-add',{note:$('serverName').value,host:$('serverHost').value,port:Number($('serverPort').value)}).then(refresh).catch(error);
async function setControllerIP(automatic){try{const address=automatic?'':$('manualIP').value.trim();if(!automatic&&!address)throw Error('请填写主控当前 IP，或点击恢复自动查找');await api('controller-address',{controller:$('manualController').value,address});$('manualStatus').textContent='已保存，正在使用原证书核验并重新连接；另一条连接不变。';await refresh()}catch(e){error(e)}}
$('manualSave').onclick=()=>setControllerIP(false);$('manualAuto').onclick=()=>setControllerIP(true);
$('shareAddress').onclick=async()=>{try{const v=await api('share-controller-address');await navigator.clipboard.writeText(v.text);$('urls').textContent='已复制，可把整段文字发给被控电脑。'}catch(e){error(e)}};
async function importAddressText(){const v=await api('import-controller-address',{invite:$('sharedAddress').value});$('importStatus').textContent='已导入 '+v.controller+' → '+v.address+'，正在核验证书并连接；请等顶部显示 2/2。';await refresh()}
$('importAddress').onclick=()=>importAddressText().catch(error);
$('pasteAddress').onclick=async()=>{const button=$('pasteAddress');button.disabled=true;try{let value;try{value=await navigator.clipboard.readText()}catch(e){$('sharedAddress').focus();$('importStatus').textContent='浏览器未允许读取剪贴板。请在框里按 Command+V 粘贴整段文字，再点“导入并连接”。';return}if(!value.includes('VSME-ADDRESS1:')&&!value.includes('VSME-ADDRESS2:'))throw Error('剪贴板没有主控连接文字，请先复制管理员发来的整段消息');$('sharedAddress').value=value;await importAddressText()}catch(e){error(e)}finally{button.disabled=false}};
function stop(){if(closing)return;closing=true;navigator.sendBeacon('/api/stop',JSON.stringify({key}));$('state').textContent='已请求关闭权限';document.querySelectorAll('button').forEach(b=>b.disabled=true)}
$('stop').onclick=stop;window.addEventListener('pagehide',()=>{if(!terminalLifecycle)stop()});refresh();setInterval(refresh,2000);
</script></html>`
